### ISSUE TITLE
Terminado diccionario

### ISSUE THREAD

**Issue by juanmagl1** [juanmagl1/tercerTrimestreProgramacion#2]
Terminado diccionario, gestion de notas y diccionario con mapas

**Comment by ioliasa** [comment]
En el diccionario normal falta el método de ver el significado de una palabra, y el ver las palabras que empiezan por.

En el diccionario de mapas, falta el método de ver los significados de una palabra.

En el de notas, ¿ para qué le pides el dni y el nombre, si con el dni ya sabes qué alumno es?
