### ISSUE TITLE
Terminado country

### ISSUE THREAD

**Issue by juanmagl1** [juanmagl1/tercerTrimestreProgramacion#4]

**Comment by ioliasa** [comment]
El programa debe crear un nuevo fichero en donde aparezca el id y el nombre de cada país, junto con el número de ciudades que hay en ese país y el númeo de direcciones que hay, de forma que **en cada pais se muestren primero las ciudades con más direcciones.**

**Comment by ioliasa** [comment]
Sigo sin ver cómo ordenas????

**Comment by juanmagl1** [comment]
Tengo un compareTo en la clase City, y lo llamo en el método, para ordenar por direcciones y en la clase Country llamo al método con el collections.sort y después lo imprimo en el fichero

**Comment by ioliasa** [comment]
OK
